### ISSUE TITLE
Add support for server minimongo

### ISSUE THREAD

**Issue by vbgm** [Goluis/cottz-publish-relations#15]
When trying to publish from server-only minimongo, following error is shown:
```
TypeError: Cannot read property 'selector' of undefined
at HandlerController.add (packages/cottz:publish-relations/lib/server/handler_controller.js:22:34)
at CursorMethods.cursor (packages/cottz:publish-relations/lib/server/cursor/cursor.js:20:34)
```

**Comment by lfades** [comment]
Maybe at some point the internal implementation of minimongo changed and [this line](https://github.com/lfades/cottz-publish-relations/blob/master/lib/server/handler_controller.js#L20) may have broke.

**Comment by vbgm** [comment]
I guess there are no plans to fix this? :-)

**Comment by lfades** [comment]
Yeah, sorry about that.

I'm not working with Meteor anymore, and even If I come back because I still think Meteor is great, I'll use Apollo Graphql instead of publish/subscribe.
